<?php

namespace IXE83\BlogBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCategory()
	{
		return $this->getEntityManager()->createQuery(
		'SELECT c.name FROM IXE83BlogBundle:Category c')
		->getResult();
	}
	
	
}
