<?php

namespace IXE83\BlogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCategory($limit = null)
	{
		$qb = $this->createQuery(
		'SELECT name FROM IXE83BlogBundle:Category c');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
            ->getResult();
	}
}
