fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
ixe83_blog:
    resource: "@IXE83BlogBundle/Resources/config/routing.yml"
    prefix:   /


user_registration:
    path:     /register
    defaults: { _controller: IXE83BlogBundle:Registration:register }
    

    
