# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        IXE83\BlogBundle\Entity\User:
            algorithm: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        our_db_provider:
            entity:
                class: IXE83BlogBundle:User
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            
            pattern: ^/
            http_basic: ~
            provider: our_db_provider
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login: 
                check_path: /login_check
                login_path: /login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
            logout:
                path: security_logout
                target: homepage
    access_control:
        - { path: /admin/.*, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
