# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.category:
            class: IXE83\BlogBundle\Admin\CategoryAdmin
            arguments: [~, IXE83\BlogBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Category }
                
    admin.blog:
        class: IXE83\BlogBundle\Admin\BlogAdmin
        arguments: [~, IXE83BlogBundle\Entity\Blog, ~]
        tags: 
            - { name: sonata.admin, manager_type: orm, label: Blog post }