IXE83_blog_post:
    resource: "@IXE83BlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

    
# src/IXE83/BlogBundle/Resources/config/routing.yml
IXE83BlogBundle_homepage:
    path:     /
    defaults: { _controller: "IXE83BlogBundle:Page:index" }
    requirements:
         methods:  GET
         
# src/IXE83/BlogBundle/Resources/config/routing.yml
IXE83BlogBundle_about:
    path:   /about
    defaults: { _controller: "IXE83BlogBundle:Page:about" }
    requirements:
         methods:  GET
         
# src/IXE83/BlogBundle/Resources/config/routing.yml
IXE83BlogBundle_contact:
    path:   /contact
    defaults: { _controller: "IXE83BlogBundle:Page:contact" }
    requirements:
         methods:  GET|POST
         
# src/IXE83/BlogBundle/Resources/config/routing.yml
IXE83BlogBundle_blog_show:
    path: /{id}/{slug}
    defaults: { _controller:"IXE83BlogBundle:Blog:show" }
    requirements:
        methods: GET
        id: \d+
        
IXE83BlogBundle_comment_create:
    path: /comment/{blog_id}
    defaults: {_controller: "IXE83BlogBundle:Comment:create" }
    requirements: 
        methods: POST
        blog_id: \d+

# src/IXE83/BlogBundle/Resources/config/routing.yml
IXE83BlogBundle_newpost:
    path: /new
    defaults: { _controller:"IXE83BlogBundle:Blog:new" }
    requirements:
        methods: GET|POST
        
# src/IXE83/BlogBundle/Resources/config/routing.yml
IXE83BlogBundle_blog_edit:
    path: /{id}/edit/
    defaults: { _controller:"IXE83BlogBundle:Blog:edit" }
    requirements:
        methods: GET|POST

# src/IXE83/BlogBundle/Resources/config/routing.yml
IXE83BlogBundle_blog_delete:
    path: /{id}/delete/
    defaults: { _controller:"IXE83BlogBundle:Blog:delete" }
    requirements:
        methods: DELETE
        
IXE83BlogBundle_category_index:
    path:     /category/
    defaults: { _controller: "IXE83BlogBundle:Category:index" }
    methods:  GET

IXE83BlogBundle_category_show:
    path:     /category/{id}/{name}
    defaults: { _controller: "IXE83BlogBundle:Category:show" }
    requirements:
        methods: GET
        id: \d+

category_new:
    path:     /category/new
    defaults: { _controller: "IXE83BlogBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /category/{name}/edit
    defaults: { _controller: "IXE83BlogBundle:Category:edit" }
    methods:  [GET, POST]

category_delete:
    path:     /category/delete/{id}
    defaults: { _controller: "IXE83BlogBundle:Category:delete" }
    requirements:
        methods:  DELETE
               
    
tag_index:
    path:     /tags/
    defaults: { _controller: "IXE83BlogBundle:Tag:index" }
    methods:  GET

tag_new:
    path:     /tags/new
    defaults: { _controller: "IXE83BlogBundle:Tag:new" }
    methods:  [GET, POST]

tag_edit:
    path:     /tags/{name}/edit
    defaults: { _controller: "IXE83BlogBundle:Tag:edit" }
    methods:  [GET, POST]

tag_delete:
    path:     /tags/{id}/delete
    defaults: { _controller: "IXE83BlogBundle:Tag:delete" }
    methods:  DELETE  

user_index:
    path:     /user/index
    defaults: { _controller: "IXE83BlogBundle:User:index" }
    methods:  GET

user_show:
    path:     /user/{id}/show
    defaults: { _controller: "IXE83BlogBundle:User:show" }
    methods:  GET

user_new:
    path:     /user/new
    defaults: { _controller: "IXE83BlogBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /user/{id}/edit
    defaults: { _controller: "IXE83BlogBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /user/{id}/delete
    defaults: { _controller: "IXE83BlogBundle:User:delete" }
    methods:  DELETE
